name: terrascan(IAC)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]


jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'gcp'
        only_warn: true
        scm_token: ${{ secrets.GITHUB_TOKEN }}
        #verbose: true
        sarif_upload: true
        #non_recursive:
        iac_dir: ./terraform/
        #policy_path:
        #skip_rules:
        #config_path:
        #find_vulnerabilities:
        #webhook_url:
        #webhook_token:
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'terrascan.sarif'
