name: Build , Push to GCR and Deploy to GKE (dev)

on:
  push:
    branches: [ "development" ]
#   pull_request:
#     branches: [ "" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: ${{ secrets.GCR_REGION }} # TODO: update region of the Artifact Registry
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}    # TODO: update to cluster name
  GKE_ZONE:   ${{ secrets.GKE_CLUSTER_REGION }} # TODO: update to cluster zone
  DEPLOYMENT_NAME: demo-app # TODO: update to deployment name
  REPOSITORY: ${{ secrets.GCP_GCR_NAME }}  # TODO: update to Artifact Registry docker repository
  IMAGE: demo-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Docker Authentication
      run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }} 
        location: ${{ secrets.GKE_CLUSTER_REGION }}

    # Build the Docker image using your Dockerfile
    - name: Build
      run: |-
        
        docker build --tag "gcr.io/microservices-arch-demo/demo-app" -f demo-app/kubernetes/base/Dockerfile . --build-arg GITHUB_SHA="$GITHUB_SHA"
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
            image-ref: 'gcr.io/microservices-arch-demo/demo-app'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH,INFO'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: 'trivy-results.sarif'
    
  # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "gcr.io/microservices-arch-demo/demo-app"
        
  # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        cp kustomize demo-app/kubernetes/base/

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
      
          cd demo-app/kubernetes/base
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$IMAGE
          ./kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment/demo-app
        

         
  
